name: Stages Demo
run-name: Demonstrating the use of multiple stages.
on: [push]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: "Getting the computer name of runner"
        run: hostname

  DeployDev:
    name: Deploy to DEV Environment
    needs: [Build]
    runs-on: self-hosted
    steps:
      - name: "Runing Docker"
        run: docker

  DeployStaging:
    name: Deploy to Staging Environment
    needs: [Build]
    runs-on: self-hosted
    steps:
      - run: echo "Deploying to Staging environment"

  DeployProd:
    name: Deploy to PROD Environment
    needs: [DeployStaging]
    runs-on: self-hosted
    steps:
      - run: echo "Deploying to PRODUCTION environment"